import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/SideNav";
import AppBody from "@/components/AppBody";
import BottomNav from "@/components/BottomNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </head>
      <body className={`h-full absolute top-0 left-0 w-screen text-white`}>
        {/* <link
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
        rel="stylesheet"
      /> */}
        <div className="bg-black overflow-hidden box-border h-full w-full flex flex-col sm:flex-row">
          <SideNav></SideNav>
          <AppBody>{children}</AppBody>
          <BottomNav></BottomNav>
        </div>
      </body>
    </html>
  );
}
